apache/incubator-nemo

- README.md
JIRA: [NEMO-29: Update GitHub main page for initial migration to ASF](https://issues.apache.org/jira/browse/NEMO-29)
- README.md modified to reflect our code migration to Apache.
- None
- Not required
- The contents below prerequisites and setup should soon move to either the website or the wiki.
> [NEMO-29] Update GitHub Main README.md

- conf/src/main/java/edu/snu/nemo/conf/JobConf.java
- runtime/driver/src/main/java/edu/snu/nemo/driver/NemoDriver.java
- runtime/executor/src/main/java/edu/snu/nemo/runtime/executor/Executor.java
- tests/src/test/java/edu/snu/nemo/tests/runtime/executor/datatransfer/DataTransferTest.java
JIRA: [NEMO-36: Make Executor Do Not Care About Capacity](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-36?filter=allopenissues)
- Made `Executor` do not care about the capacity but only driver do.
- No changes.
- Existing ITCases cover this change.
- No comments.
> [NEMO-36] Make Executor Do Not Care About Capacity

- runtime/executor/src/main/java/edu/snu/nemo/runtime/executor/TaskGroupExecutor.java
- runtime/executor/src/main/java/edu/snu/nemo/runtime/executor/bytetransfer/ByteInputContext.java
- runtime/executor/src/main/java/edu/snu/nemo/runtime/executor/bytetransfer/ByteTransport.java
- runtime/executor/src/main/java/edu/snu/nemo/runtime/executor/data/BlockManagerWorker.java
JIRA: [NEMO-39](https://issues.apache.org/jira/browse/NEMO-39)
- Minor changes to meet SonarCloud criteria (including interrupting threads when `InterruptedException` occurs).
- None
- Existing tests cover the changes.
- None
resolves [NEMO-39](https://issues.apache.org/jira/browse/NEMO-39)
> [NEMO-39] SonarCloud Bugs and Vulnerabilities for RuntimeExecutor

- .travis.yml
- bin/sonar_qube.sh
- compiler/frontend/spark/src/main/java/edu/snu/nemo/compiler/frontend/spark/sql/SparkSession.java
- pom.xml
JIRA: [NEMO-43: Sonar cloud script](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-43)
- Add sonar qube script to run sonar analysis locally with maven
- Minor change to check whether or not sonar qube detects the change made to fix sonar analysis.
- Minor change to travis script to automatically retry builds that are failed due to resource constraints.
- Existing ITCases cover this change.
- No comments.
resolves [NEMO-43](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-43)
> [NEMO-43] Sonar cloud script

- runtime/master/src/main/java/edu/snu/nemo/runtime/master/JobStateManager.java
- runtime/master/src/main/java/edu/snu/nemo/runtime/master/RuntimeMaster.java
- runtime/master/src/main/java/edu/snu/nemo/runtime/master/resource/ExecutorRepresenter.java
- runtime/master/src/main/java/edu/snu/nemo/runtime/master/scheduler/BatchSingleJobScheduler.java
- runtime/master/src/main/java/edu/snu/nemo/runtime/master/scheduler/ExecutorRegistry.java
- runtime/master/src/main/java/edu/snu/nemo/runtime/master/scheduler/PendingTaskCollection.java
- runtime/master/src/main/java/edu/snu/nemo/runtime/master/scheduler/Scheduler.java
- runtime/master/src/main/java/edu/snu/nemo/runtime/master/scheduler/SchedulerRunner.java
- runtime/master/src/main/java/edu/snu/nemo/runtime/master/scheduler/SingleJobTaskCollection.java
- runtime/master/src/test/java/edu.snu.nemo.runtime.master/scheduler/BatchSingleJobSchedulerTest.java
- runtime/master/src/test/java/edu.snu.nemo.runtime.master/scheduler/FaultToleranceTest.java
- runtime/master/src/test/java/edu.snu.nemo.runtime.master/scheduler/SchedulerTestUtil.java
- runtime/master/src/test/java/edu.snu.nemo.runtime.master/scheduler/SingleTaskQueueTest.java
- tests/src/test/java/edu/snu/nemo/tests/runtime/executor/datatransfer/DataTransferTest.java
JIRA: [NEMO-46: Make the operations on ExecutorRegistry atomic](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-46)
- Make ExecutorRegistry thread-safe
- Create many failures in FaultToleranceTest#testTaskReexecutionForFailure, instead of a single failure
- Track per-task attempts
- Ignore all task state change notifications from executors for previous task attempts. This can happen due to the nature of asynchronous notifications. For example, the master can receive a notification that an executor has been removed, and then a notification that the task that was running in the removed executor has been completed. In this case, if we do not look at the attempt number, the state changes from FAILED_RECOVERABLE to COMPLETED, which is …
> [NEMO-46] Make the operations on ExecutorRegistry atomic

- runtime/master/src/main/java/edu/snu/nemo/runtime/master/scheduler/CompositeSchedulingPolicy.java
- runtime/master/src/main/java/edu/snu/nemo/runtime/master/scheduler/MinOccupancyFirstSchedulingPolicy.java
- runtime/master/src/main/java/edu/snu/nemo/runtime/master/scheduler/SourceLocationAwareSchedulingPolicy.java
- runtime/master/src/test/java/edu/snu/nemo/runtime/master/scheduler/MinOccupancyFirstSchedulingPolicyTest.java
JIRA: [NEMO-74: Rename RoundRobinSchedulingPolicy](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-74)
- Rename RoundRobinSchedulingPolicy to MinOccupancyFirstSchedulingPolicy
- N/A
- This PR does not include tests because the changes do not affect any functionality.
- N/A
resolves [NEMO-74](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-74)
> [NEMO-74] Rename RoundRobinSchedulingPolicy to MinOccupancyFirstSchedulingPolicy

- common/src/main/java/edu/snu/nemo/common/coder/IntCoder.java
- common/src/main/java/edu/snu/nemo/common/coder/PairCoder.java
- runtime/common/src/main/java/edu/snu/nemo/runtime/common/RuntimeTestUtil.java
- runtime/common/src/test/java/edu/snu/nemo/runtime/common/message/local/LocalMessageTest.java
- runtime/common/src/test/java/edu/snu/nemo/runtime/common/optimizer/pass/runtime/DataSkewRuntimePassTest.java
- runtime/executor/pom.xml
- runtime/executor/src/test/java/edu/snu/nemo/runtime/executor/data/BlockStoreTest.java
- runtime/executor/src/test/java/edu/snu/nemo/runtime/executor/data/BlockTransferConnectionQueueTest.java
- runtime/executor/src/test/java/edu/snu/nemo/runtime/executor/datatransfer/DataTransferTest.java
JIRA: [NEMO-83: Move /tests/runtime into /runtime/tests](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-83)
- This PR moves the tests/runtime to nemo-runtime-[common|executor]
- New Coders (PairCoder, IntCoder) in tests have been added to remove the dependency on Beam
- `e.s.n.tests.runtime.common.plan.DAGConverterTest` stays in place due to the complex dependency; as per discussion with @johnyangk, we decided to revisit this test in another issue.
- N/A  
- N/A
resolves [NEMO-83](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-83)
> [NEMO-83] Move /tests/runtime into /runtime/tests

- runtime/common/src/main/java/edu/snu/nemo/runtime/common/message/ncs/NcsMessageEnvironment.java
- runtime/common/src/main/proto/ControlMessage.proto
- runtime/common/src/test/java/edu/snu/nemo/runtime/common/message/local/LocalMessageTest.java
- runtime/executor/src/main/java/edu/snu/nemo/runtime/executor/Executor.java
- runtime/executor/src/main/java/edu/snu/nemo/runtime/executor/MetricManagerWorker.java
- runtime/executor/src/main/java/edu/snu/nemo/runtime/executor/MetricMessageSender.java
- runtime/executor/src/test/java/edu/snu/nemo/runtime/executor/datatransfer/DataTransferTest.java
- runtime/master/src/main/java/edu/snu/nemo/runtime/master/MetricManagerMaster.java
- runtime/master/src/main/java/edu/snu/nemo/runtime/master/RuntimeMaster.java
- runtime/master/src/main/java/edu/snu/nemo/runtime/master/scheduler/ExecutorRegistry.java
- tests/src/test/java/edu/snu/nemo/runtime/master/MetricCollectionTest.java
- tests/src/test/java/edu/snu/nemo/runtime/master/MetricFlushTest.java
JIRA: [NEMO-61: Fix lost execution metric collection problem](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-61)
- Add metric flush request and response types in control message type.
- `RuntimeMaster#terminate` now wait until all metrics from executors arrive.
- Expose `ExecutorReqistry#viewExecutors` to public.
- MetricFlushTest ensures MetricManagerMaster can send flush requests to MetricManagerWorkers and workers respond appropriately by flushing remaining metric logs.
- Related to NEMO-20.
resolves [NEMO-61](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-61)
> [NEMO-61] Fix lost execution metric collection problem

- README.md
JIRA: [NEMO-163: Update README.md to use Hadoop 2.7.2](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-163)
- N/A
- Updated README.md to use Hadoop 2.7.2.
- N/A
- Some features of Nemo won't be available under Hadoop 2.7.2. Since the REEF implementation we depend on uses Hadoop 2.7.2, we'd better update README for newcomers to use Hadoop 2.7.2.
resolves [NEMO-163](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-163)
> [NEMO-163] Update README.md to use Hadoop 2.7.2

- runtime/executor/src/main/java/edu/snu/nemo/runtime/executor/task/TaskExecutor.java
JIRA: [NEMO-165: Bug when a task reads from multiple parent tasks](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-165)
- In TaskExecutor#handleDataFetchers, initialize "int finishedFetcherIndex" in each looping, and not outside the loop.
- N/A
- N/A
- N/A
resolves [NEMO-165](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-165)
> [NEMO-165] Bug when a task reads from multiple parent tasks

- compiler/optimizer/src/main/java/edu/snu/nemo/compiler/optimizer/pass/compiletime/annotating/NodeNamesAssignmentPass.java
- runtime/master/src/main/java/edu/snu/nemo/runtime/master/scheduler/NodeShareSchedulingConstraint.java
JIRA: [NEMO-166: Do not attach NodeNamesProperty to Source Stages](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-166)
- Attaching NodeNamesProperty to source stages makes scheduling source tasks virtually impossible, if the assigned node does not have the corresponding source split. This PR prevents NodeNameAssignmentPass not to assign node names on source stages.
- N/A
- N/A
- Integration tests on distributed environment is desired.
resolves [NEMO-166](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-166)
> [NEMO-166] Do not attach NodeNamesProperty to Source Stages

- runtime/executor/src/main/java/edu/snu/nemo/runtime/executor/data/DataUtil.java
- runtime/executor/src/main/java/edu/snu/nemo/runtime/executor/data/block/FileBlock.java
- runtime/executor/src/main/java/edu/snu/nemo/runtime/executor/datatransfer/InputReader.java
- runtime/executor/src/main/java/edu/snu/nemo/runtime/executor/datatransfer/OutputWriter.java
- runtime/executor/src/test/java/edu/snu/nemo/runtime/executor/datatransfer/DataTransferTest.java
JIRA: [NEMO-176: Improve sequential read from disk](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-176)
- Read whole data to read from file stream first and decode them later in `FileBlock`
- Remove `limit` parameter in `InputStreamIterator` of `DataUtil` and make `DataUtil#deserializePartition` to limit the stream itself by the partition size.
- Remove the assumption that "the source and destination parallelism of One-to-One communication is always 1" in `OutputWriter` and `InputReader`
- Existing `DataTransferTest`, `BlockStoreTest` and other unit tests cover this change.
- Existing integration tests also cover this change.
- N/A.
resolves …
> [NEMO-176] Improve sequential read from disk

- common/src/main/java/edu/snu/nemo/common/coder/BytesDecoderFactory.java
- common/src/test/java/edu/snu/nemo/common/coder/CoderFactoryTest.java
JIRA: [NEMO-177: Fix BytesDecoder to handle empty stream properly](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-177)
- Make `BytesDecoder` of `BytesDecoderFactory` to return empty byte[] at first, and throw EoF for the next time if it receives empty byte array.
- N/A.
- Add `CoderFactoryTest` to test this feature.
- N/A.
resolves [NEMO-177](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-177)
> [NEMO-177] Fix BytesDecoder to handle empty stream properly

- compiler/frontend/beam/src/main/java/edu/snu/nemo/compiler/frontend/beam/transform/DoTransform.java
- pom.xml
JIRA: [NEMO-184: Upgrade to Beam 2.6.0](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-184)
- Upgrade to Beam 2.6.0
- N/A
- N/A (just a version upgrade)
- throw UnsupportedException when the new Row-related APIs are called
resolves [NEMO-184](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-184)
> [NEMO-184] Upgrade to Beam 2.6.0

- compiler/backend/src/main/java/edu/snu/nemo/compiler/backend/nemo/NemoBackend.java
- runtime/common/src/main/java/edu/snu/nemo/runtime/common/eventhandler/DynamicOptimizationEvent.java
- runtime/common/src/main/java/edu/snu/nemo/runtime/common/eventhandler/DynamicOptimizationEventHandler.java
- runtime/common/src/main/java/edu/snu/nemo/runtime/common/optimizer/RunTimeOptimizer.java
- runtime/common/src/main/java/edu/snu/nemo/runtime/common/optimizer/pass/runtime/DataSkewRuntimePass.java
- runtime/common/src/main/java/edu/snu/nemo/runtime/common/optimizer/pass/runtime/RuntimePass.java
- runtime/common/src/main/java/edu/snu/nemo/runtime/common/plan/PhysicalPlan.java
- runtime/common/src/main/java/edu/snu/nemo/runtime/common/plan/StageEdge.java
- runtime/executor/src/main/java/edu/snu/nemo/runtime/executor/datatransfer/InputReader.java
- runtime/master/src/main/java/edu/snu/nemo/runtime/master/scheduler/BatchScheduler.java
- runtime/test/src/main/java/edu/snu/nemo/runtime/common/plan/TestPlanGenerator.java
JIRA: [NEMO-192: Remove IRDAG from PhysicalPlan](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-192)
- Removed IRDAG from PhysicalPlan
- N/A
- N/A
- Now dynamic optimization is done via StageEdge. We need a revised version of IR-based dynamic optimization, considering issues related with RDD caching and reshaping IR DAG in run-time. This will be handled with issue [NEMO-193](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-193).
resolves [NEMO-192](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-192)
> [NEMO-192] Remove IRDAG from PhysicalPlan

- common/src/main/java/edu/snu/nemo/common/Cloneable.java
- common/src/main/java/edu/snu/nemo/common/ir/vertex/IRVertex.java
- common/src/main/java/edu/snu/nemo/common/ir/vertex/InMemorySourceVertex.java
- common/src/main/java/edu/snu/nemo/common/ir/vertex/LoopVertex.java
- common/src/main/java/edu/snu/nemo/common/ir/vertex/MetricCollectionBarrierVertex.java
- common/src/main/java/edu/snu/nemo/common/ir/vertex/OperatorVertex.java
- common/src/main/java/edu/snu/nemo/common/ir/vertex/SourceVertex.java
- common/src/main/java/edu/snu/nemo/common/test/EmptyComponents.java
- compiler/frontend/beam/src/main/java/edu/snu/nemo/compiler/frontend/beam/source/BeamBoundedSourceVertex.java
- compiler/frontend/spark/src/main/java/edu/snu/nemo/compiler/frontend/spark/source/SparkDatasetBoundedSourceVertex.java
- compiler/frontend/spark/src/main/java/edu/snu/nemo/compiler/frontend/spark/source/SparkTextFileBoundedSourceVertex.java
JIRA: [NEMO-89: Clean up IRVertex#getClone()](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-89)
- `getClone()` has been moved into a Interface
- Copy constructors has been added to the subclasses of the `IRVertex` which does the deep copying of the objects
- NA
- NA
- NA
resolves [NEMO-89](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-89)
> [NEMO-89] Clean up IRVertex#getClone()

- .github/pull_request_template.md
JIRA: [NEMO-197: Automatically close JIRA issues upon closing PRs](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-197)
- None
- This minor PR updates the final line of the PR template, to automatically close the issue using GitHub.
- N/A
- N/A
Closes #110
> [NEMO-197] Close JIRA issues upon closing PRs

- compiler/frontend/beam/src/main/java/org/apache/nemo/compiler/frontend/beam/transform/CreateViewTransform.java
JIRA: [NEMO-218: Throws exception while processing non-keyed events in CreateViewTransform](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-218)
- remove `if` clause in `CreateViewTransform`.onData()
- 
- 
- 
Closes #121
> [NEMO-218] Throws exception while processing non-keyed events in CreateViewTransform

- .travis.yml
- pom.xml
JIRA: [NEMO-248: Validate javadoc in mvn phase](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-248)
- Add javadoc validation to validate phase
- Remove mvn javdoc:javdoc in .travis.yml
- 
- 
- 
Closes #139
> [NEMO-248] Validate javadoc in mvn phase

- common/src/main/java/org/apache/nemo/common/punctuation/Watermark.java
- compiler/frontend/beam/src/main/java/org/apache/nemo/compiler/frontend/beam/transform/AbstractDoFnTransform.java
- compiler/frontend/beam/src/main/java/org/apache/nemo/compiler/frontend/beam/transform/DoFnTransform.java
- compiler/frontend/beam/src/main/java/org/apache/nemo/compiler/frontend/beam/transform/GroupByKeyAndWindowDoFnTransform.java
- compiler/test/src/test/java/org/apache/nemo/compiler/frontend/beam/transform/GroupByKeyAndWindowDoFnTransformTest.java
JIRA: [NEMO-267: Consider watermark holds in GroupByKeyAndWindowDoFnTransform](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-267)
- Fix `GroupByKeyAndWindowDoFnTransform` to emit output watermarks by holding watermarks for each key 
- Fix `GroupByKeyAndWindowDoFnTransform` by using sliding windows
> [NEMO-267] Consider watermark holds in GroupByKeyAndWindowDoFnTransform

- compiler/frontend/beam/src/main/java/org/apache/nemo/compiler/frontend/beam/transform/GroupByKeyTransform.java
JIRA: [NEMO-275: Eager Garbage Collection for GroupByKey](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-275)
- Instead of iterating over the accumulated elements and then clearing out all the elements at once, remove the elements while iterating
> [NEMO-275] Eager Garbage Collection for GroupByKey

- compiler/frontend/beam/src/main/java/org/apache/nemo/compiler/frontend/beam/source/BeamUnboundedSourceVertex.java
JIRA: [NEMO-279: Finish BeamUnboundedSource when emitting TIMESTAMP_MAX_VALUE](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-279)
- Set `isFinished` true in `BeamUnboundedSourceVertex` when emitting `TIMESTAMP_MAX_VALUE` in watermark.
> [NEMO-279] Finish BeamUnboundedSource when emitting TIMESTAMP_MAX_VALUE

- pom.xml
JIRA: [NEMO-303: Use Surefire 3.0.0-M1](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-303)
- POM: Use maven-surefire-plugin 3.0.0-M1 and maven-failsafe-plugin 3.0.0-M1
**Notes**
- See SUREFIRE-1588 for the relevant bug report at the ASF Jira system
> [NEMO-303] Use Surefire 3.0.0-M1

- common/src/main/java/org/apache/nemo/common/dag/DAGBuilder.java
- common/src/main/java/org/apache/nemo/common/ir/edge/executionproperty/MetricCollectionProperty.java
- compiler/optimizer/src/main/java/org/apache/nemo/compiler/optimizer/pass/compiletime/reshaping/SkewReshapingPass.java
- examples/beam/src/test/java/org/apache/nemo/examples/beam/NetworkTraceAnalysisITCase.java
- runtime/common/src/main/java/org/apache/nemo/runtime/common/eventhandler/DynamicOptimizationEvent.java
- runtime/common/src/main/java/org/apache/nemo/runtime/common/eventhandler/DynamicOptimizationEventHandler.java
- runtime/common/src/main/java/org/apache/nemo/runtime/common/optimizer/RunTimeOptimizer.java
- runtime/common/src/main/java/org/apache/nemo/runtime/common/optimizer/pass/runtime/DataSkewRuntimePass.java
- runtime/common/src/main/java/org/apache/nemo/runtime/common/partitioner/DataSkewHashPartitioner.java
- runtime/common/src/test/java/org/apache/nemo/runtime/common/optimizer/pass/runtime/DataSkewRuntimePassTest.java
- runtime/master/src/main/java/org/apache/nemo/runtime/master/scheduler/BatchScheduler.java
JIRA: [NEMO-327: Fix skew handling for multi shuffle edge receive](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-327)
- For the case that a vertex receives multiple shuffle edges, makes `DataSkewPolicy` collect metric data for the shuffle edges in a single metric aggregation vertex and optimize the edges at once.
- Makes runtime pass receive multiple target edges.
- Adds an integration test with the data skew policy for `NetworkTraceAnalysis` that has a join.
- N/A.
Closes #189
> [NEMO-327] Fix skew handling for multi shuffle edge receiver

- README.md
- bin/run_beam.sh
- bin/run_nexmark.sh
- client/pom.xml
- client/src/main/java/org/apache/nemo/client/beam/BeamStateTranslator.java
- client/src/main/java/org/apache/nemo/client/beam/NemoPipelineResult.java
- client/src/main/java/org/apache/nemo/client/beam/NemoRunner.java
- client/src/main/java/org/apache/nemo/client/beam/NemoRunnerRegistrar.java
- compiler/frontend/beam/pom.xml
- compiler/frontend/beam/src/main/java/org/apache/nemo/compiler/frontend/beam/InMemorySideInputReader.java
- compiler/frontend/beam/src/main/java/org/apache/nemo/compiler/frontend/beam/PipelineVisitor.java
- compiler/frontend/beam/src/main/java/org/apache/nemo/compiler/frontend/beam/source/BeamUnboundedSourceVertex.java
- examples/beam/pom.xml
- examples/beam/src/main/java/org/apache/nemo/examples/beam/AlternatingLeastSquare.java
- examples/beam/src/main/java/org/apache/nemo/examples/beam/AlternatingLeastSquareInefficient.java
- examples/beam/src/main/java/org/apache/nemo/examples/beam/Broadcast.java
- examples/beam/src/main/java/org/apache/nemo/examples/beam/MinimalWordCount.java
- examples/beam/src/main/java/org/apache/nemo/examples/beam/MultinomialLogisticRegression.java
- examples/beam/src/main/java/org/apache/nemo/examples/beam/NemoPipelineOptionsFactory.java
- examples/beam/src/main/java/org/apache/nemo/examples/beam/NetworkTraceAnalysis.java
- examples/beam/src/main/java/org/apache/nemo/examples/beam/PartitionWordsByLength.java
- examples/beam/src/main/java/org/apache/nemo/examples/beam/PerKeyMedian.java
- examples/beam/src/main/java/org/apache/nemo/examples/beam/PerPercentileAverage.java
- examples/beam/src/main/java/org/apache/nemo/examples/beam/SimpleSumSQL.java
- examples/beam/src/main/java/org/apache/nemo/examples/beam/WindowedBroadcast.java
- examples/beam/src/main/java/org/apache/nemo/examples/beam/WindowedWordCount.java
- examples/beam/src/main/java/org/apache/nemo/examples/beam/WordCount.java
- examples/nexmark/pom.xml
- examples/pom.xml
JIRA: [NEMO-353: Launch NEXMark applications](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-353)
- Remove nemo-client dependency from nemo-compiler-frontend-beam and create shaded-client.jar file to include it for the execution of NEXMark jobs. 
- Create an example package that contains NEXMark jar file. 
- Fix NullPointerException in `BeamUnboundedSourceVertex` when executing NEXMark applications. 
-Update README
> [NEMO-353] Launch NEXMark applications

- compiler/frontend/beam/src/main/java/org/apache/nemo/compiler/frontend/beam/PipelineTranslator.java
JIRA: [NEMO-356: Visualize the name of beam transform in DAG
](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-356)
- populate the name of Beam transform.
The visualized DAGs have been uploaded to https://issues.apache.org/jira/projects/NEMO/issues/NEMO-356
> [NEMO-356] Visualize the name of beam transform in DAG

- README.md
JIRA: [NEMO-357: Fix broken link on README](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-357)
- None
- Fixes the broken sonar cloud link on the README
- N/A
- None
Closes #200
> [NEMO-357] Fix broken link on README

- common/src/main/java/org/apache/nemo/common/ir/IdManager.java
- common/src/main/java/org/apache/nemo/common/ir/vertex/IRVertex.java
- common/src/main/java/org/apache/nemo/common/ir/vertex/LoopVertex.java
- common/src/main/java/org/apache/nemo/common/ir/vertex/OperatorVertex.java
- compiler/optimizer/src/main/java/org/apache/nemo/compiler/optimizer/pass/compiletime/reshaping/LoopExtractionPass.java
JIRA: [NEMO-358: Recycling vertex ids while cloning a vertex](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-358)
- Implementation on the IDManager so that it saves the IDs that are no longer used, to be reused later on.
- Fixes the LoopExtractionPass (where cloning occurs) to meet with the new implementations.
- None
- Existing tests confirm the changes.
- None
Closes #201
> [NEMO-358] Recycling vertex ids while cloning a vertex 

- common/src/main/java/org/apache/nemo/common/DirectByteArrayOutputStream.java
- common/src/main/java/org/apache/nemo/common/coder/BytesDecoderFactory.java
- runtime/executor/src/main/java/org/apache/nemo/runtime/executor/data/DataUtil.java
- runtime/executor/src/main/java/org/apache/nemo/runtime/executor/data/partition/SerializedPartition.java
JIRA: [NEMO-369: DirectByteArrayOutputStream usage refactoring](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-369)
- Replaced usage of duplicated method getCount() to size()
- deleted getCount() method
- None
- None
- None
> [NEMO-369] DirectByteArrayOutputStream usage refactoring

- client/src/main/java/org/apache/nemo/client/JobLauncher.java
JIRA: [NEMO-368: NEMO-353 breaks the application from running in YARN environments](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-368)
- includes all jar files in the class path when starting NemoDriver
> [NEMO-368] include all jar files for global libraries

- compiler/test/src/test/java/org/apache/nemo/compiler/frontend/beam/transform/TestOutputCollector.java
- pom.xml
- runtime/executor/src/test/java/org/apache/nemo/runtime/executor/data/BlockStoreTest.java
- runtime/executor/src/test/java/org/apache/nemo/runtime/executor/data/BlockTest.java
- runtime/executor/src/test/java/org/apache/nemo/runtime/executor/task/TaskExecutorTest.java
- runtime/master/src/test/java/org/apache/nemo/runtime/master/BlockManagerMasterTest.java
- runtime/master/src/test/java/org/apache/nemo/runtime/master/PlanStateManagerTest.java
- runtime/master/src/test/java/org/apache/nemo/runtime/master/scheduler/BatchSchedulerTest.java
- runtime/master/src/test/java/org/apache/nemo/runtime/master/scheduler/LocalitySchedulingConstraintTest.java
JIRA: [NEMO-379: Change javadoc goal to a proper one](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-379)
- Change javadoc test command from `javadoc` to `test-javadoc`. This prevents tests from creating unwanted javdoc files, caused by #139 .
- None
- None
- None
Closes #212
> [NEMO-379] Change javadoc goal to a proper one

- common/src/main/java/org/apache/nemo/common/DirectByteBufferOutputStream.java
- common/src/test/java/org/apache/nemo/common/BBOutputStreamTest.java
- common/src/test/java/org/apache/nemo/common/DirectByteBufferOutputStreamTest.java
JIRA: [NEMO-383: Implement DirectByteBufferOutputStream for Off-heap SerializedMemoryStore](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-383)
- Added `DirectByteBufferOuputStream` for writing data off-heap.
- Added `DirectByteBufferOutputStreamTest` to test proper write using the `DirectByteBufferOutputStream`.
> [NEMO-383] Implement DirectByteBufferOutputStream for Off-heap SerializedMemoryStore

- runtime/common/src/main/java/org/apache/nemo/runtime/common/message/MessageEnvironment.java
JIRA: [NEMO-391: Set GrpcMessageEnvironment as a default implementation](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-391)
- Change the default implementation of MessageEnvironment to GrpcMessageEnvironment
> [NEMO-391] Set GrpcMessageEnvironment as a default implementation

- pom.xml
JIRA: [NEMO-402: Broken guava version conflicts cause ERROR: Trying to remove a RunningJob that is unknown ](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-###)
- guava version 19.0 -> 20.0
Please refer to JIRA description for the bug report details.
> [NEMO-402] Fix guava version conflict

- runtime/executor/src/main/java/org/apache/nemo/runtime/executor/data/MemoryChunk.java
JIRA: [NEMO-412: Address Sonar Cloud issue for MemoryChunk](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-412)
- `checkIndex()` in `MemoryChunk` is fixed to return either true or false.
- type length for byte access using UNSAFE when calling `checkIndex()` changed to 1.
> [NEMO-412] Address Sonar Cloud issue for MemoryChunk

- runtime/executor/src/main/java/org/apache/nemo/runtime/executor/data/MemoryChunk.java
JIRA: [NEMO-413: Fix index checking for byte access of MemoryChunk using UNSAFE](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-413)
- Index checking for byte operation using UNSAFE fixed: type size for byte changed from 0 to 1.
> [NEMO-413] Fix index checking for byte access of MemoryChunk using UNSAFE

- client/src/main/java/org/apache/nemo/client/JobLauncher.java
- conf/src/main/java/org/apache/nemo/conf/DataPlaneConf.java
- runtime/driver/src/main/java/org/apache/nemo/driver/NemoDriver.java
JIRA: [NEMO-414: Command-line specified runtime data plane configurations not applied](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-414)
- User-specified data plane configuration now applies to parameters.
- The number of serialization threads for scheduling(schedule_ser_thread) now can be set through the command-line argument.
> [NEMO-414] Command-line specified runtime data plane configurations not applied

- client/src/main/java/org/apache/nemo/client/JobLauncher.java
- conf/src/main/java/org/apache/nemo/conf/DataPlaneConf.java
- conf/src/main/java/org/apache/nemo/conf/JobConf.java
- runtime/executor/src/test/java/org/apache/nemo/runtime/executor/data/BlockStoreTest.java
- runtime/executor/src/test/java/org/apache/nemo/runtime/executor/datatransfer/DataTransferTest.java
JIRA: [NEMO-397: Separation of JVM heap region and off-heap memory region](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-397)
- Off-heap memory ratio option added
- slack region reserved for off-heap memory region by adding the two
> [NEMO-397] Separation of JVM heap region and off-heap memory region

- common/src/test/java/org/apache/nemo/common/DAGTest.java
- compiler/frontend/spark/src/main/java/org/apache/nemo/compiler/frontend/spark/transform/ReduceByKeyTransform.java
- compiler/frontend/spark/src/main/java/org/apache/nemo/compiler/frontend/spark/transform/ReduceTransform.java
- runtime/common/src/main/java/org/apache/nemo/runtime/common/metric/MetricUtils.java
- runtime/executor/src/main/java/org/apache/nemo/runtime/executor/data/stores/MemoryStore.java
- runtime/executor/src/main/java/org/apache/nemo/runtime/executor/data/stores/SerializedMemoryStore.java
- runtime/master/src/main/java/org/apache/nemo/runtime/master/scheduler/BatchScheduler.java
JIRA: [NEMO-429: SWPP TEAM 3 Code Smell Fix](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-429)
- Fixed code smells(SWPP Code Smell Session) 
**Notes:**
- We doubt if just adding `transient` prefix is good solution, so we didn't fix about it. Please let us know if it should be fixed.
By [Team3](https://github.com/swsnu/swpp2019-team3)
P.S. One of our members was absent today.
> [NEMO-429] SWPP TEAM3 Code Smell Fix

- checkstyle.xml
- common/src/main/java/org/apache/nemo/common/ir/edge/executionproperty/SubPartitionSetProperty.java
- common/src/main/java/org/apache/nemo/common/ir/vertex/executionproperty/EnableDynamicTaskSizingProperty.java
- runtime/common/src/main/java/org/apache/nemo/runtime/common/metric/JobMetric.java
- runtime/common/src/main/java/org/apache/nemo/runtime/common/metric/TaskMetric.java
- runtime/common/src/main/java/org/apache/nemo/runtime/common/plan/Stage.java
- runtime/common/src/main/java/org/apache/nemo/runtime/common/plan/StageEdge.java
- runtime/executor/src/main/java/org/apache/nemo/runtime/executor/TaskStateManager.java
- runtime/executor/src/main/java/org/apache/nemo/runtime/executor/datatransfer/BlockInputReader.java
- runtime/executor/src/main/java/org/apache/nemo/runtime/executor/datatransfer/IntermediateDataIOFactory.java
- runtime/executor/src/main/java/org/apache/nemo/runtime/executor/datatransfer/PipeInputReader.java
- runtime/executor/src/main/java/org/apache/nemo/runtime/executor/task/TaskExecutor.java
- runtime/executor/src/test/java/org/apache/nemo/runtime/executor/datatransfer/DataTransferTest.java
- runtime/executor/src/test/java/org/apache/nemo/runtime/executor/task/TaskExecutorTest.java
JIRA: [NEMO-433: Improvement of Task Metrics and Collecting Them For Sampling](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-433)
- Added some new metrics (task, job) and usages of them
- Added new execution property for DTS (vertex, edge)
- changed checkstyle grammer for windows 
- BlockInputReader now contains metricMessageSender for sending some task metrics, and it has whole task id instead of just task index.
- Tests related to BlockInputReader has changed: TaskExecutorTest, DataTransferTest
- N/A
Closes #289
> [NEMO-433] Improvement of Task Metrics and Collecting Them For Sampling

- .travis.yml
- pom.xml
JIRA: [NEMO-440: Migrate to Java11 and use Java 11 Features](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-440)
- Upgrade POM and modify travis to check Java 11
- None
- None
- None
Closes #291
> [NEMO-440] Migrate to Java11 and use Java 11 Features

- README.md
JIRA: [NEMO-440: Migrate to Java11 and use Java 11 Features](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-440)
- Update readme
- None
- None
- Java 11 support has been done in PR #291
- Nemo build fails with Java 8 due to the pom configuration that does not work with Java 8
> [Nemo-440] Update README.md about java 11 support

- .travis.yml
- README.md
- pom.xml
- Fixes Travis CI script that have been failing due to gpg error
- Bring back support for Java 8, as Hadoop and REEF still needs support for Java 8 (reverts #291)
- None
- N/A
- None
Closes #296
> [MINOR] Fix Travis CI + Bring back support for Java 8

- bin/run_beam.sh
- runtime/driver/src/main/java/org/apache/nemo/driver/NemoDriver.java
- runtime/master/src/main/java/org/apache/nemo/runtime/master/RuntimeMaster.java
- runtime/master/src/main/java/org/apache/nemo/runtime/master/metric/MetricStore.java
- runtime/master/src/main/java/org/apache/nemo/runtime/master/scheduler/ExecutorRegistry.java
- 
- Change yarn command in run_beam.sh file to avoid conflict with javascript package manager
- Split metric saving part from flushMetric function and call metric saving part after waiting metric flush
- 
- 
Closes #GITHUB_PR_NUMBER
> [MINOR] Avoid yarn conflict + Save Metrics after waiting to get full data 

- .travis.yml
- None
- It adds installation of node dependencies with LTS version
- Existing tests comply
- Node on versions 18 newly requires manual installation of other libraries on Ubuntu servers
Closes #331
> [MINOR] Fix Travis script to run with LTS node version
