.travis.yml

JIRA: [NEMO-34](https://issues.apache.org/jira/browse/NEMO-34)
- Edit Travis.yml to support sonarcloud at https://sonarcloud.io/organizations/apache-nemo/projects
- None.
- Not required.
- None

[NEMO-34] SonarCloud

---

.travis.yml
compiler/frontend/beam/src/main/java/edu/snu/nemo/compiler/frontend/beam/NemoPipelineVisitor.java
compiler/frontend/spark/src/main/java/edu/snu/nemo/compiler/frontend/spark/core/java/SparkFrontendUtils.java
compiler/frontend/spark/src/main/java/edu/snu/nemo/compiler/frontend/spark/sql/SparkSession.java
compiler/frontend/spark/src/main/java/edu/snu/nemo/compiler/frontend/spark/transform/CollectTransform.java
examples/beam/src/main/java/edu/snu/nemo/examples/beam/AlternatingLeastSquare.java
examples/spark/src/main/java/edu/snu/nemo/examples/spark/sql/JavaSparkSQLExample.java

JIRA: [NEMO-40](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-40)
- Fixes travis script to build SonarCloud only for the master branch.
- Others are minor changes to meet SonarCloud criteria.
- changes code in slight ways to use try-with-resources statements
- Existing tests cover the changes.
- None

[NEMO-40] Solve SonarCloud issues for Frontend and Examples

---

.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md
.github/pull_request_template.md
README.md

JIRA: [NEMO-31: Meet community standards](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-31)
- Adds Code of Conduct, Contributing, and Pull Request Template to our repository.
- Adds a line to redirect users to the contributing guideline on the README.md
- No tests required.
- None.
resolves [NEMO-31](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-31)

[NEMO-31] Community Standards

---

runtime/common/src/main/java/edu/snu/nemo/runtime/common/plan/Task.java
runtime/executor/src/main/java/edu/snu/nemo/runtime/executor/Executor.java
runtime/executor/src/main/java/edu/snu/nemo/runtime/executor/TaskExecutor.java
runtime/executor/src/main/java/edu/snu/nemo/runtime/executor/TaskStateManager.java
runtime/master/src/main/java/edu/snu/nemo/runtime/master/resource/ExecutorRepresenter.java
runtime/master/src/main/java/edu/snu/nemo/runtime/master/scheduler/BatchSingleJobScheduler.java
runtime/master/src/main/java/edu/snu/nemo/runtime/master/scheduler/CompositeSchedulingPolicy.java
runtime/master/src/main/java/edu/snu/nemo/runtime/master/scheduler/ContainerTypeAwareSchedulingPolicy.java
runtime/master/src/main/java/edu/snu/nemo/runtime/master/scheduler/FreeSlotSchedulingPolicy.java
runtime/master/src/main/java/edu/snu/nemo/runtime/master/scheduler/PendingTaskCollection.java
runtime/master/src/main/java/edu/snu/nemo/runtime/master/scheduler/RoundRobinSchedulingPolicy.java
runtime/master/src/main/java/edu/snu/nemo/runtime/master/scheduler/SchedulerRunner.java
runtime/master/src/main/java/edu/snu/nemo/runtime/master/scheduler/SchedulingPolicy.java
runtime/master/src/main/java/edu/snu/nemo/runtime/master/scheduler/SingleJobTaskCollection.java
runtime/master/src/main/java/edu/snu/nemo/runtime/master/scheduler/SourceLocationAwareSchedulingPolicy.java
runtime/master/src/test/java/edu/snu/nemo/runtime/master/scheduler/ContainerTypeAwareSchedulingPolicyTest.java
runtime/master/src/test/java/edu/snu/nemo/runtime/master/scheduler/FreeSlotSchedulingPolicyTest.java
runtime/master/src/test/java/edu/snu/nemo/runtime/master/scheduler/RoundRobinSchedulingPolicyTest.java
runtime/master/src/test/java/edu/snu/nemo/runtime/master/scheduler/SingleTaskQueueTest.java
runtime/master/src/test/java/edu/snu/nemo/runtime/master/scheduler/SourceLocationAwareSchedulingPolicyTest.java
tests/src/test/java/edu/snu/nemo/tests/runtime/executor/TaskExecutorTest.java

JIRA: [NEMO-95: Rename ExecutableTask to Task](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-95)
- Rename ExecutableTask to Task
- N/A
- N/A
- N/A
resolves [NEMO-95](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-95)

[NEMO-95] Rename ExecutableTask to Task

---

runtime/master/src/main/java/edu/snu/nemo/runtime/master/BlockManagerMaster.java

JIRA: [NEMO-108: SonarCloud Bugs and Vulnerabilities for Nemo Runtime Master](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-108)
- Handle `InterruptedException` properly
resolves [NEMO-108](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-108)

[Nemo 108] SonarCloud Bugs and Vulnerabilities for Nemo Runtime Master

---

client/src/main/java/edu/snu/nemo/client/ClientEndpoint.java

JIRA: [NEMO-115: SonarCloud Bugs and Vulnerabilities for Nemo Client](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-115)
- Handled `InterruptedException` properly
resolves [NEMO-115](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-115)

[NEMO-115] SonarCloud Bugs and Vulnerabilities for Nemo Client

---

runtime/common/src/main/java/edu/snu/nemo/runtime/common/message/PersistentConnectionToMasterMap.java

JIRA: [NEMO-112: SonarCloud Bugs and Vulnerabilities for Nemo Runtime Common](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-112)
- Handled `InterruptedException` properly
resolves [NEMO-112](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-112)

[NEMO-112] SonarCloud Bugs and Vulnerabilities for Nemo Runtime Common

---

runtime/executor/src/main/java/edu/snu/nemo/runtime/executor/data/BlockManagerWorker.java
runtime/executor/src/main/java/edu/snu/nemo/runtime/executor/task/ParentTaskDataFetcher.java
runtime/executor/src/main/java/edu/snu/nemo/runtime/executor/task/TaskExecutor.java

JIRA: [NEMO-107: SonarCloud Bugs and Vulnerabilities for Nemo Runtime Executor](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-107)
- Resolve reported bugs and vulnerabilities of Nemo Runtime Executor from SonarCloud.
resolves [NEMO-107](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-107)

[NEMO-107] SonarCloud Bugs and Vulnerabilities for Nemo Runtime Executor

---

README.md

JIRA: [NEMO-113: Update README](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-113)
- Fix broken links in README.md
- n/a
- n/a
- n/a
resolves [NEMO-113](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-113)

[NEMO-113] Update README

---

runtime/common/src/main/java/edu/snu/nemo/runtime/common/exception/AbsentBlockException.java
runtime/common/src/main/java/edu/snu/nemo/runtime/common/state/BlockState.java
runtime/common/src/main/proto/ControlMessage.proto
runtime/executor/src/main/java/edu/snu/nemo/runtime/executor/data/BlockManagerWorker.java
runtime/executor/src/test/java/edu/snu/nemo/runtime/executor/data/BlockStoreTest.java
runtime/master/src/main/java/edu/snu/nemo/runtime/master/BlockManagerMaster.java
runtime/master/src/main/java/edu/snu/nemo/runtime/master/BlockMetadata.java
runtime/master/src/main/java/edu/snu/nemo/runtime/master/scheduler/BatchSingleJobScheduler.java
runtime/master/src/test/java/edu/snu/nemo/runtime/master/BlockManagerMasterTest.java

JIRA: [NEMO-87: Remove unused BlockStates](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-87)
- READY, LOST_BEFORE_COMMIT, LOST, REMOVED => NOT_AVAILABLE
- SCHEDULED => IN_PROGRESS
- COMMITTED => AVAILABLE
- N/A
- N/A (no new feature)
- N/A
resolves [NEMO-87](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-87)

[NEMO-87] Remove unused BlockStates

---

.travis.yml

JIRA: [NEMO-240: Fix .travis.yml](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-240)
- set `sudo` to `required` and change the license header
- 
- 
- 
Closes #133

[Nemo-240] Fix .travis.yml

---

.travis.yml
examples/beam/src/test/java/org/apache/nemo/examples/beam/PerKeyMedianITCase.java
runtime/executor/src/main/java/org/apache/nemo/runtime/executor/datatransfer/DataFetcherOutputCollector.java
runtime/executor/src/main/java/org/apache/nemo/runtime/executor/datatransfer/OperatorVertexOutputCollector.java
runtime/executor/src/main/java/org/apache/nemo/runtime/executor/task/DataFetcher.java
runtime/executor/src/main/java/org/apache/nemo/runtime/executor/task/ParentTaskDataFetcher.java
runtime/executor/src/main/java/org/apache/nemo/runtime/executor/task/SourceVertexDataFetcher.java
runtime/executor/src/main/java/org/apache/nemo/runtime/executor/task/TaskExecutor.java
runtime/executor/src/test/java/org/apache/nemo/runtime/executor/task/ParentTaskDataFetcherTest.java

JIRA: [NEMO-238: Optimize processElement in TaskExecutor](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-238)
- Refactor `processElement` by creating `DataFetcherOutputCollector`
- 
- 
- 
Closes #131

[Nemo-238] Optimize processElement in TaskExecutor

---

client/src/main/java/org/apache/nemo/client/JobLauncher.java

JIRA: [NEMO-241: Powered by NEMO](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-241)
- Adds an ASCII art for Nemo job launching
```
Powered by
_   __                   
/ | / /__  ____ ___  ____ 
/  |/ / _ \/ __ `__ \/ __ \
/ /|  /  __/ / / / / / /_/ /
/_/ |_/\___/_/ /_/ /_/\____/ 
```
- N/A
- N/A

[NEMO-241] ASCII art for Nemo job launching

---

compiler/frontend/beam/pom.xml
compiler/frontend/spark/pom.xml
compiler/optimizer/pom.xml
compiler/pom.xml
compiler/test/pom.xml
examples/beam/pom.xml
examples/pom.xml
examples/spark/pom.xml
pom.xml
runtime/common/pom.xml
runtime/driver/pom.xml
runtime/executor/pom.xml
runtime/master/pom.xml
runtime/pom.xml
runtime/test/pom.xml

JIRA: [NEMO-242: Parent POM.xmls for /compiler, /runtime, and /examples](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-242)
- Make parent pom.xmls for /compiler, /runtime, and /examples
- 
- 
- 
Closes #144

[NEMO-242] Parent POM.xmls for \compiler, \runtime, and \examples

---

compiler/frontend/beam/src/main/java/org/apache/nemo/compiler/frontend/beam/NemoPipelineOptions.java
compiler/frontend/beam/src/main/java/org/apache/nemo/compiler/frontend/beam/transform/AbstractDoFnTransform.java
compiler/frontend/beam/src/main/java/org/apache/nemo/compiler/frontend/beam/transform/DoFnTransform.java
compiler/frontend/beam/src/main/java/org/apache/nemo/compiler/frontend/beam/transform/GroupByKeyAndWindowDoFnTransform.java
compiler/test/src/test/java/org/apache/nemo/compiler/frontend/beam/transform/DoFnTransformTest.java
examples/beam/src/test/java/org/apache/nemo/examples/beam/WindowedWordCountITCase.java

JIRA: [NEMO-268: Consider start/finish bundles in Transform](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-268)
- Add `checkAndInvokeBundle` and `checkAndFinishBundle` methods to `AbstractDoFnTransform`
- Use the methods in `DoFnTransform` and `GroupByKeyAndWindowDoFnTransform`
- Add getters/setters for count and millis bundles to `NemoPipelineOptions` 
- Add `testCountBundle()` and `testTimeBundle()` to `DoFnTransformTest`

[NEMO-268] Consider start/finish bundles in Transform

---

examples/beam/src/main/java/org/apache/nemo/examples/beam/GenericSourceSink.java
examples/beam/src/main/java/org/apache/nemo/examples/beam/MultinomialLogisticRegression.java

JIRA: [NEMO-272: Fix incorrect uses of Beam FinishBundle](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-272)
- Fixs GenericSourceSink
- Fixs MultinomialLogisticRegression
- Adds TODOs for fixing the root causes

[NEMO-272] Fix incorrect uses of Beam FinishBundle

---

.gitignore
pom.xml

JIRA: [NEMO-283: Add an Exclusion Rule for RAT Plugin](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-283)
- Modifies POM (Adds an exclusion rule for RAT plugin)
- N/A
- N/A (The build suffices)
- N/A

[NEMO-283] Exclude DAG files from RAT

---

DISCLAIMER

JIRA: [NEMO-305: Add Disclaimer](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-305)
- Adds the disclaimer file as per Apache's standards (https://incubator.apache.org/guides/branding.html#disclaimers)
- N/A
- N/A
- N/A

[NEMO-305] Add DISCLAIMER

---

compiler/optimizer/src/main/java/org/apache/nemo/compiler/optimizer/policy/StreamingPolicy.java

JIRA: [NEMO-311: Add StreamingPolicy](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-311)
- Add StreamingPolicy that uses PipeTransferForAllEdgesPass

[NEMO-311] Add StreamingPolicy

---

client/pom.xml
common/pom.xml
compiler/backend/pom.xml
compiler/frontend/beam/pom.xml
compiler/frontend/spark/pom.xml
compiler/optimizer/pom.xml
compiler/pom.xml
compiler/test/pom.xml
conf/pom.xml
examples/beam/pom.xml
examples/pom.xml
examples/spark/pom.xml
pom.xml
runtime/common/pom.xml
runtime/driver/pom.xml
runtime/executor/pom.xml
runtime/master/pom.xml
runtime/pom.xml
runtime/test/pom.xml

JIRA: [NEMO-323: Upgrade current working version to 0.2-SNAPSHOT](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-323)
- Upgrades the current working version to 0.2-SNAPSHOT as v0.1 has been released.
- N/A
- N/A
- v0.1 has been released.

[NEMO-323] Upgrade current working version to 0.2-SNAPSHOT

---

.github/COMMITTING.md
.github/CONTRIBUTING.md

JIRA: [NEMO-322: Committer's Guide](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-322)
- None
- Adds a committer's guide to the repository
- N/A
- None
Closes #186

[NEMO-322] Committer's Guide

---

.travis.yml
README.md
runtime/master/src/test/java/org/apache/nemo/runtime/master/PlanStateManagerTest.java

JIRA: [NEMO-340: SonarCloud for PRs](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-340)
- Parallelization on Travis builds are enabled to speed up our builds.
- Tokens are used as Travis environment variables, so that it is kept private and encrypted by itself.
- README now has a status badge on the quality of the code.
- Increase of the timeout for the test that frequently gets timed out.
- Existing tests confirm the changes
- Analysis on external PRs are still ongoing ([link](https://docs.travis-ci.com/user/sonarcloud/))
Closes #194

[NEMO-340] SonarCloud for PRs

---

common/src/main/java/org/apache/nemo/common/Util.java
common/src/main/java/org/apache/nemo/common/ir/vertex/CachedSourceVertex.java
common/src/main/java/org/apache/nemo/common/ir/vertex/InMemorySourceVertex.java
common/src/main/java/org/apache/nemo/common/ir/vertex/SourceVertex.java
common/src/main/java/org/apache/nemo/common/test/EmptyComponents.java
compiler/frontend/beam/src/main/java/org/apache/nemo/compiler/frontend/beam/source/BeamBoundedSourceVertex.java
compiler/frontend/beam/src/main/java/org/apache/nemo/compiler/frontend/beam/source/BeamUnboundedSourceVertex.java
compiler/frontend/spark/src/main/java/org/apache/nemo/compiler/frontend/spark/source/SparkDatasetBoundedSourceVertex.java
compiler/frontend/spark/src/main/java/org/apache/nemo/compiler/frontend/spark/source/SparkTextFileBoundedSourceVertex.java
runtime/common/src/main/java/org/apache/nemo/runtime/common/metric/JobMetric.java
runtime/executor/src/test/java/org/apache/nemo/runtime/executor/task/TaskExecutorTest.java
runtime/master/src/main/java/org/apache/nemo/runtime/master/metric/MetricStore.java

JIRA: [NEMO-359: Implementation of getEstimatedSizeBytes in SourceVertex](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-359)
- Addition of getEstimatedSizeBytes on the SourceVertex interface
- Implementation of the method for the bounded sources.
- None
- N/A
- None
Closes #202

[NEMO-359] Implementation of getEstimatedSizeBytes in SourceVertex

---

README.md
conf/src/main/java/org/apache/nemo/conf/JobConf.java
pom.xml
runtime/master/src/main/java/org/apache/nemo/runtime/master/RuntimeMaster.java

JIRA: [NEMO-375: Add option to turn off metric collection to DB](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-375)
- Adds configuration for the DB to turn off metric collection to DB by default.
- Adds proper README docs
- None
- None
- None
Closes #211

[NEMO-375] Add option to turn off metric collection to DB

---

runtime/master/src/main/java/org/apache/nemo/runtime/master/scheduler/AntiAffinitySchedulingConstraint.java
runtime/master/src/main/java/org/apache/nemo/runtime/master/scheduler/BatchScheduler.java
runtime/master/src/main/java/org/apache/nemo/runtime/master/scheduler/LocalitySchedulingConstraint.java
runtime/master/src/main/java/org/apache/nemo/runtime/master/scheduler/NodeShareSchedulingConstraint.java
runtime/master/src/main/java/org/apache/nemo/runtime/master/scheduler/TaskDispatcher.java

JIRA: [NEMO-395: Address SonarCloud issues for the scheduler package](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-395)
- Fixes all "Critical" issues
- Fixes most of the "Major" issues

[NEMO-395] Address SonarCloud issues for the scheduler package

---

compiler/optimizer/src/main/java/org/apache/nemo/compiler/optimizer/pass/compiletime/annotating/XGBoostPass.java
runtime/common/src/main/java/org/apache/nemo/runtime/common/metric/MetricUtils.java

JIRA: [NEMO-422: Sonarcloud issues](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-422)
- None
- Minor fixes for SonarCloud
- N/A
- None
Closes #242

[NEMO-422] Sonarcloud bugs

---

.gitignore
pom.xml

JIRA: [NEMO-428: Ignore .factorypath for rat check and version control](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-428)
- None
- Ignore .factorypath for rat check and version control
- None
- None

[NEMO-428] Ignore .factorypath for rat check and version control

---

compiler/optimizer/src/main/java/org/apache/nemo/compiler/optimizer/pass/compiletime/annotating/ResourceSitePass.java
examples/beam/src/main/java/org/apache/nemo/examples/beam/NetworkTraceAnalysis.java
runtime/common/src/main/java/org/apache/nemo/runtime/common/plan/PhysicalPlanGenerator.java
runtime/executor/src/main/java/org/apache/nemo/runtime/executor/bytetransfer/ByteInputContext.java
runtime/executor/src/main/java/org/apache/nemo/runtime/executor/bytetransfer/ByteOutputContext.java
runtime/executor/src/main/java/org/apache/nemo/runtime/executor/bytetransfer/ByteTransferContext.java
runtime/executor/src/main/java/org/apache/nemo/runtime/executor/data/DataUtil.java

JIRA: [NEMO-422: SonarCloud issues](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-422)
- None
- ResourceSitePass: Fixed an operand in arithmetic expression to express its type explicitly.
- example/NetworkTraceAnalysis: Replaced at-most-one-iteration loop with if-else.
- PhysicalPlanGenerator: Use isPresent instead of orElseThrow for sanity checks.
- bytetransfer: Removed 'volatile' for object types.
- Existing tests should be sufficient.
- None

[NEMO-422] Address code quality issues for ResourceSitePass, NetworkTraceAnalysis, PhysicalPlanGenerator, and bytetransfer

---

common/src/main/java/org/apache/nemo/common/ir/IRDAG.java
compiler/optimizer/src/main/java/org/apache/nemo/compiler/optimizer/pass/compiletime/annotating/DefaultParallelismPass.java

JIRA: [NEMO-422: SonarCloud issues](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-422)
- Fix some SonarCloud bugs related to `Optional`
- None
- None
- None
Closes #247

Fix SonarCloud bugs related to Optional

---

runtime/common/src/main/java/org/apache/nemo/runtime/common/metric/MetricUtils.java

JIRA: [NEMO-422: Sonarcloud issue](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-422)
- None
- Gets rid of the hard-coded fake password, and handles it with Base64 decoding method.
- Existing tests confirm the changes
- None
Closes #246

[NEMO-422] Sonarcloud issue

---

client/pom.xml
common/pom.xml
compiler/backend/pom.xml
compiler/frontend/beam/pom.xml
compiler/frontend/spark/pom.xml
compiler/optimizer/pom.xml
compiler/optimizer/src/main/java/org/apache/nemo/compiler/optimizer/examples/MapReduceDisaggregationOptimization.java
compiler/pom.xml
compiler/test/pom.xml
conf/pom.xml
examples/beam/pom.xml
examples/nexmark/pom.xml
examples/pom.xml
examples/spark/pom.xml
pom.xml
runtime/common/pom.xml
runtime/driver/pom.xml
runtime/executor/pom.xml
runtime/master/pom.xml
runtime/pom.xml
runtime/test/pom.xml

JIRA: [NEMO-421: Release v0.2](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-421)
- Update the versions of components according to the release v0.2.
- N/A
- N/A
- I'll open a release vote current version.  If it passed, I'll update the versions to `0.3-SNAPSHOT` and merge this PR. Please do not merge any other PR before the vote. Thanks :)
Closes #421

[NEMO-421] Release v0.2

---

client/pom.xml
common/pom.xml
compiler/backend/pom.xml
compiler/frontend/beam/pom.xml
compiler/frontend/spark/pom.xml
compiler/optimizer/pom.xml
compiler/optimizer/src/main/java/org/apache/nemo/compiler/optimizer/examples/MapReduceDisaggregationOptimization.java
compiler/pom.xml
compiler/test/pom.xml
conf/pom.xml
examples/beam/pom.xml
examples/nexmark/pom.xml
examples/pom.xml
examples/spark/pom.xml
pom.xml
runtime/common/pom.xml
runtime/driver/pom.xml
runtime/executor/pom.xml
runtime/master/pom.xml
runtime/pom.xml
runtime/test/pom.xml

This reverts commit 0cab1dc36f5193a223b0ea448d7a41f9732ef06e.
JIRA: [NEMO-421: Release v0.2](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-421)
- Revert the 0.2 release commit, which has been merged by mistake.
- 
- 
- I'll make a new PR for the release

Revert "[NEMO-421] Release v0.2 (#286)"

---

client/pom.xml
common/pom.xml
compiler/backend/pom.xml
compiler/frontend/beam/pom.xml
compiler/frontend/spark/pom.xml
compiler/optimizer/pom.xml
compiler/pom.xml
compiler/test/pom.xml
conf/pom.xml
examples/beam/pom.xml
examples/nexmark/pom.xml
examples/pom.xml
examples/spark/pom.xml
pom.xml
runtime/common/pom.xml
runtime/driver/pom.xml
runtime/executor/pom.xml
runtime/master/pom.xml
runtime/pom.xml
runtime/test/pom.xml

JIRA: [NEMO-439: Upgrade current working version to 0.3-SNAPSHOT](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-439)
- Upgrades the current working version to 0.3-SNAPSHOT as v0.2 has been released.
- N/A
- N/A
- v0.2 has been released.

[Nemo-439] Upgrade current working version to 0.3-SNAPSHOT

---

examples/beam/pom.xml

JIRA: [NEMO-447: Fix beam pom.xml to resolve build failure](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-447)
**Major Changes:**
* changed examples/beam/pom.xml to resolve build failure

[NEMO-447] Fix beam pom.xml to resolve build failure

---

compiler/test/src/test/java/org/apache/nemo/compiler/frontend/beam/transform/CombineFnTest.java

JIRA: [NEMO-457: Improve test coverage score on sonar cloud test](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-457)
- Added unit tests for partial and final CombineFn.
- 
- 
- 
Closes #GITHUB_PR_NUMBER

[NEMO-457] Improve test coverage score on sonar cloud test

---

README.md
bin/install_nemo.sh

- Adds an installation script to the Nemo repository
- None
- Tested on my Mac and ubuntu machine
- None

[MINOR] Installation Script

---

.travis.yml
pom.xml
runtime/executor/src/main/java/org/apache/nemo/runtime/executor/transfer/FrameDecoder.java

- None
- This upgrades the travis build environment from trusty (v14) to bionic (v18) (ubuntu)
- Existing tests comply
- None
Closes #332

[MINOR] Upgrade travis build VM from trusty (v14) to bionic (v18)

---

client/pom.xml
common/pom.xml
common/src/main/java/org/apache/nemo/common/ir/vertex/transform/LatencymarkEmitTransform.java
common/src/main/java/org/apache/nemo/common/ir/vertex/transform/StreamTransform.java
compiler/backend/pom.xml
compiler/frontend/beam/pom.xml
compiler/frontend/spark/pom.xml
compiler/optimizer/pom.xml
compiler/pom.xml
compiler/test/pom.xml
conf/pom.xml
examples/beam/pom.xml
examples/nexmark/pom.xml
examples/pom.xml
examples/spark/pom.xml
pom.xml
runtime/common/pom.xml
runtime/driver/pom.xml
runtime/executor/pom.xml
runtime/master/pom.xml
runtime/pom.xml
runtime/test/pom.xml

- Bump Apache Nemo version to 0.5-snapshot, due to the release of v0.4
- None
- Existing tests comply
- None

Nemo Release 0.4

---

.asf.yaml
.travis.yml

- Travis builds are failing due to Node.js version problems. I've fixed this in this commit.
- Java 8 testing is dropped for Travis - will be migrated to github actions.
- Existing tests comply.
- None
Closes #341

[MINOR] Fix failing builds

---

.asf.yaml
.github/workflows/maven.yml
.github/workflows/sonarcloud.yml

- Removes unallowed actions from the maven workflow
- Updates the sonarcloud token variable to meet the name provided by apache software foundation
- None
- Existing tests
- None
Closes #343

[MINOR] Fix apache-related issues with GitHub actions
